// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFS5JD_YuQYa0jIDGWZFeAD21klojB2S0',
    appId: '1:587134338987:web:759f4970af6bf1abcdb4ee',
    messagingSenderId: '587134338987',
    projectId: 'gifty-3b7c1',
    authDomain: 'gifty-3b7c1.firebaseapp.com',
    storageBucket: 'gifty-3b7c1.appspot.com',
    measurementId: 'G-TD1FP00L8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2fAlDh4piPeAZvWBjE17_hHtiOMTJtRE',
    appId: '1:587134338987:android:89c1fee2f8c6332dcdb4ee',
    messagingSenderId: '587134338987',
    projectId: 'gifty-3b7c1',
    storageBucket: 'gifty-3b7c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWguy37zelwUg1WPfuhAT6TkiAjaZ6nc',
    appId: '1:587134338987:ios:2aa214dfba2365f3cdb4ee',
    messagingSenderId: '587134338987',
    projectId: 'gifty-3b7c1',
    storageBucket: 'gifty-3b7c1.appspot.com',
    iosBundleId: 'com.example.gifty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADWguy37zelwUg1WPfuhAT6TkiAjaZ6nc',
    appId: '1:587134338987:ios:cadf0c4643d21383cdb4ee',
    messagingSenderId: '587134338987',
    projectId: 'gifty-3b7c1',
    storageBucket: 'gifty-3b7c1.appspot.com',
    iosBundleId: 'com.example.gifty.RunnerTests',
  );
}
